[package]
name = "tars-stream"
version = "0.0.1"
authors = ["zerolocust <zerolocust@gmail.com>"]
description = "for tars stream decode/encode"

[dependencies]
bytes = "0.4"
quick-error = "1.2.2"

[dev-dependencies]
uuid = { version = "0.6", features = ["v4"] }
rand = "0.5"