// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.2.11 by WSRD Tencent.
// Generated from `/data/NodejsServer/NodejsDeployServer/jce/uploads/1513674297835/in/ChannelCodeStruct.jce'
// **********************************************************************

"use strict";

var assert    = require("assert");
var TafStream = require("@tencent/taf-stream");

var WePlusChannelCode = WePlusChannelCode || {};
module.exports.WePlusChannelCode = WePlusChannelCode;


WePlusChannelCode.ChannelCodeStruct = function() {
    this.channelCode = 0;
    this.createTime = 0;
    this._classname = "WePlusChannelCode.ChannelCodeStruct";
};
WePlusChannelCode.ChannelCodeStruct._classname = "WePlusChannelCode.ChannelCodeStruct";
WePlusChannelCode.ChannelCodeStruct._write = function (os, tag, value) { os.writeStruct(tag, value); }
WePlusChannelCode.ChannelCodeStruct._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
WePlusChannelCode.ChannelCodeStruct._readFrom = function (is) {
    var tmp = new WePlusChannelCode.ChannelCodeStruct();
    tmp.channelCode = is.readInt32(0, true, 0);
    tmp.createTime = is.readInt32(1, false, 0);
    return tmp;
};
WePlusChannelCode.ChannelCodeStruct.prototype._writeTo = function (os) {
    os.writeInt32(0, this.channelCode);
    os.writeInt32(1, this.createTime);
};
WePlusChannelCode.ChannelCodeStruct.prototype._equal = function () {
    assert.fail("this structure not define key operation");
}
WePlusChannelCode.ChannelCodeStruct.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
}
WePlusChannelCode.ChannelCodeStruct.prototype.toObject = function() { 
    return {
        "channelCode" : this.channelCode,
        "createTime" : this.createTime
    };
}
WePlusChannelCode.ChannelCodeStruct.prototype.readFromObject = function(json) { 
    json.hasOwnProperty("channelCode") && (this.channelCode = json.channelCode);
    json.hasOwnProperty("createTime") && (this.createTime = json.createTime);
}
WePlusChannelCode.ChannelCodeStruct.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
WePlusChannelCode.ChannelCodeStruct.new = function () {
    return new WePlusChannelCode.ChannelCodeStruct();
}
WePlusChannelCode.ChannelCodeStruct.create = function (is) {
    return WePlusChannelCode.ChannelCodeStruct._readFrom(is);
}



